# $FreeBSD$

.include <src.opts.mk>

LIB=	sysdecode

SRCS=	utrace.c
INCS=	sysdecode.h

#CFLAGS+= -I${.CURDIR} -I${.CURDIR}/../libc/gen/

#MAN+=	sysdecode_get_flags_format.3 \
#	sysdecode_get_int_format.3 \
#	sysdecode_utrace.3
#MLINKS+=sysdecode_get_flags_format.3 sysdecode_set_flags_format.3 \
#	sysdecode_get_int_format.3 sysdecode_set_int_format.3

.include <bsd.lib.mk>
