.\"
.\" Copyright (c) 2015 John Baldwin <jhb@FreeBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd November 2, 2015
.Dt sysdecode_freebsd 3
.Os
.Sh NAME
.Nm sysdecode_cloudabi64 ,
.Nm sysdecode_freebsd ,
.Nm sysdecode_freebsd32 ,
.Nm sysdecode_linux ,
.Nm sysdecode_linux32
.Nd lookup name of system calls
.Sh LIBRARY
.Lb libsysdecode
.Sh SYNOPSIS
.Ft const char *
.Fn sysdecode_cloudabi64 "unsigned int code"
.Ft const char *
.Fn sysdecode_freebsd "unsigned int code"
.Ft const char *
.Fn sysdecode_freebsd32 "unsigned int code"
.Ft const char *
.Fn sysdecode_linux "unsigned int code"
.Ft const char *
.Fn sysdecode_linux32 "unsigned int code"
.Sh DESCRIPTION
These functions return a pointer to the name of a system call identified by
.Fa code
for different process ABIs.
If
.Fa code
specifies an unknown system call,
these functions return
.Dv NULL .
.Pp
The
.Fn sysdecode_freebsd
function returns the name of the native FreeBSD system call identified by
.Fa code .
.Pp
The
.Fn sysdecode_freebsd32
function returns the name of the 32-bit FreeBSD system call identified by
.Fa code .
This function is only supported on amd64 and powerpc64.
.Pp
The
.fn sysdecode_cloudabi64
function returns the name of the 64-bit CloudABI system call identified by
.Fa code .
This function is only supported on amd64.
.Pp
The
.Fn sysdecode_linux
function returns the name of the native Linux system call identified by
.Fa code .
This function is only supported on amd64 and i386.
.Pp
The
.Fn sysdecode_linux32
function returns the name of the 32-bit Linux system call identified by
.Fa code .
This function is only supported on amd64.
.Sh RETURN VALUES
These functions return a pointer to a string on success or
.Dv NULL
if
.Fa code
is unknown.
.Sh SEE ALSO
.Xr sysdecode 3
